// --- INSTRUCTIONS ---
// 1. Place this script in a `scripts/` directory in your project root.
// 2. Make sure `umas.json` (generated by the perl scripts) is in your project root.
// 3. Create an empty `data/` directory in your `js/` directory if it doesn't exist.
// 4. Run this script from your project root: `node scripts/prepare-umas.js`
// 5. It will generate a `js/data/uma-list.json` file.

const fs = require('fs');
const path = require('path');

const umasPath = path.join(__dirname, '../raw_data/umas.json');
const outputPath = path.join(__dirname, '../js/data/uma-list.json');

console.log('Reading uma data from umas.json...');
const umasData = JSON.parse(fs.readFileSync(umasPath, 'utf8'));

const umaList = [];

for (const id in umasData) {
    const uma = umasData[id];
    // The name is the second element in the name array
    const name = uma.name[1];
    if (name) {
        // Use name_en to be consistent with skill-list.json
        umaList.push({
            id: id,
            name_en: name
        });
    }
}

// Sort alphabetically by name
umaList.sort((a, b) => a.name_en.localeCompare(b.name_en));

// Ensure the output directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, JSON.stringify(umaList, null, 2));

console.log(`Successfully processed ${umaList.length} umas.`);
console.log(`Output saved to: ${outputPath}`);